const resourceSeedState = {
  deployments: [
    {
      id: 'dep-fin-01',
      name: 'Finance identity mesh',
      blueprintId: 'active-directory',
      environment: 'Production',
      location: 'corp.east / finance',
      mode: 'agentless',
      status: 'healthy',
      decoys: 38,
      interactions: 4,
      updatedAt: '2026-09-21T13:41:00.000Z',
    },
    {
      id: 'dep-cloud-02',
      name: 'AWS production veil',
      blueprintId: 'cloud',
      environment: 'AWS / us-east-1',
      location: 'prod-platform',
      mode: 'cloud-native',
      status: 'healthy',
      decoys: 26,
      interactions: 2,
      updatedAt: '2026-09-21T13:36:00.000Z',
    },
    {
      id: 'dep-ai-03',
      name: 'AI platform guardrails',
      blueprintId: 'ai-infrastructure',
      environment: 'Kubernetes',
      location: 'ml-platform / gpu-west',
      mode: 'sensor',
      status: 'learning',
      decoys: 17,
      interactions: 1,
      updatedAt: '2026-09-21T13:28:00.000Z',
    },
    {
      id: 'dep-end-04',
      name: 'Executive endpoint shield',
      blueprintId: 'endpoint',
      environment: 'Windows',
      location: 'executive-device-group',
      mode: 'package',
      status: 'attention',
      decoys: 12,
      interactions: 3,
      updatedAt: '2026-09-21T12:54:00.000Z',
    },
  ],
  incidents: [
    {
      id: 'INC-2481',
      severity: 'critical',
      title: 'Deceptive AWS key invoked from unmanaged host',
      source: '172.22.14.38',
      target: 'ci-prod-backup',
      technique: 'T1552.001',
      confidence: 99,
      status: 'contained',
      age: '4m',
      timestamp: '2026-09-21T13:42:00.000Z',
      summary: 'A seeded cloud credential was enumerated from a developer workstation and used against the decoy STS endpoint.',
      steps: ['Credential file read', 'STS GetCallerIdentity', 'Decoy S3 listing', 'Host isolated by EDR'],
    },
    {
      id: 'INC-2479',
      severity: 'high',
      title: 'LLM agent traversed synthetic admin share',
      source: '10.42.7.19',
      target: 'FIN-JUMP-04',
      technique: 'T1021.002',
      confidence: 97,
      status: 'investigating',
      age: '18m',
      timestamp: '2026-09-21T13:28:00.000Z',
      summary: 'Automation-like SMB discovery and rapid credential reuse matched an agentic attack sequence.',
      steps: ['Share enumeration', 'Honeyfile opened', 'Credential extracted', 'Decoy service login'],
    },
    {
      id: 'INC-2476',
      severity: 'medium',
      title: 'Kerberoast request for honey service account',
      source: '10.18.2.44',
      target: 'svc_erp_archive',
      technique: 'T1558.003',
      confidence: 94,
      status: 'triaged',
      age: '47m',
      timestamp: '2026-09-21T12:59:00.000Z',
      summary: 'A SPN-backed honey account was requested from a workstation outside the approved administrator segment.',
      steps: ['LDAP enumeration', 'SPN discovered', 'TGS requested', 'SIEM case created'],
    },
    {
      id: 'INC-2471',
      severity: 'low',
      title: 'Honey document opened by approved scanner',
      source: '10.4.1.12',
      target: 'FY27_Board_Plan.xlsx',
      technique: 'T1083',
      confidence: 72,
      status: 'closed',
      age: '2h',
      timestamp: '2026-09-21T11:44:00.000Z',
      summary: 'The interaction was traced to the approved DLP scanner and added to the safe list.',
      steps: ['File enumerated', 'Beacon resolved', 'Scanner identified', 'Source allowlisted'],
    },
  ],
  sensors: [
    { id: 'sen-east-01', name: 'East datacenter', type: 'projection', version: '0.9.4', health: 100, latency: 18, address: '10.42.0.18', lastSeen: '12s ago' },
    { id: 'sen-aws-01', name: 'AWS production', type: 'cloud-native', version: '0.9.4', health: 100, latency: 31, address: 'us-east-1', lastSeen: '19s ago' },
    { id: 'sen-azure-01', name: 'Azure identity', type: 'projection', version: '0.9.3', health: 96, latency: 44, address: 'eastus2', lastSeen: '36s ago' },
    { id: 'sen-plant-01', name: 'Factory edge', type: 'rugged', version: '0.9.4', health: 89, latency: 72, address: '10.88.4.10', lastSeen: '2m ago' },
  ],
  domains: [
    { id: 'dom-1', name: 'corp.east', forest: 'corp.global', controllers: 4, honeyObjects: 148, status: 'protected' },
    { id: 'dom-2', name: 'corp.west', forest: 'corp.global', controllers: 3, honeyObjects: 96, status: 'protected' },
    { id: 'dom-3', name: 'lab.internal', forest: 'lab.internal', controllers: 2, honeyObjects: 42, status: 'learning' },
  ],
  integrations: [
    { id: 'int-splunk', name: 'Splunk Enterprise Security', category: 'SIEM', status: 'connected', lastSync: '2m ago' },
    { id: 'int-crowdstrike', name: 'CrowdStrike Falcon', category: 'EDR', status: 'connected', lastSync: '1m ago' },
    { id: 'int-tines', name: 'Tines', category: 'SOAR', status: 'connected', lastSync: '5m ago' },
    { id: 'int-defender', name: 'Microsoft Defender XDR', category: 'XDR', status: 'available', lastSync: '—' },
  ],
  tokens: [],
  sensorEnrollmentTokens: [],
  sensorCommands: [],
  sensorEvents: [],
  secrets: [],
};

export const defaultOrganizationId = 'org-default';

export const seedState = {
  organizations: [
    {
      id: defaultOrganizationId,
      name: 'AIDecepticon Demo',
      slug: 'aidecepticon-demo',
      status: 'active',
      plan: 'enterprise',
      createdAt: '2026-09-21T12:00:00.000Z',
    },
    {
      id: 'org-managed-lab',
      name: 'Managed Customer Lab',
      slug: 'managed-customer-lab',
      status: 'active',
      plan: 'managed',
      createdAt: '2026-09-21T12:00:00.000Z',
    },
  ],
  ...Object.fromEntries(Object.entries(resourceSeedState).map(([resource, items]) => [
    resource,
    items.map((item) => ({ ...item, organizationId: defaultOrganizationId })),
  ])),
};
